{{- $fullName := include "project-template.fullname" . -}}
{{- $buildtype := .Values.buildtype -}}
{{- $hasCustomDomains := contains ("TRUE") (include "project-template.filteredcustomdomains" .) -}}
{{- if and (.Values.customhosts) (.Values.servePublicly) ($hasCustomDomains) -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: {{ include "project-template.namespace" . }}
  name: {{ include "project-template.fullname" . }}-custom
  labels:
    {{- include "project-template.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  # CNAME records must exist for all custom hostnames
  tls:
    - hosts:
      {{range .Values.customhosts }}
        {{- if and (.tls) (eq .buildtype $buildtype) -}}
        - {{ .host | quote }}
      secretName: {{ .host }}
        {{- end -}}
      {{ end }}

  rules:
    {{range .Values.customhosts }}
    {{- if eq .buildtype $buildtype -}}
    - host: {{ .host | quote }}
      http:
        paths: {{ range .paths }}
          - path: {{ .path }}
            backend:
              servicePort: {{ .port }}
              serviceName: {{ $fullName }}
          {{ end }}
    {{ end }}
    {{ end }}

{{ end }}