{{ if .Values.gitlabImage }}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "project-template.image-pull-secret-data" . }}
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "project-template.image-pull-secret-name" . }}
  labels:
    {{- include "project-template.labels" . | nindent 4 }}
{{ end }}