{{- if .Values.servePublicly -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: {{ include "project-template.namespace" . }}
  name: {{ include "project-template.fullname" . }}
  labels:
    {{- include "project-template.labels" . | nindent 4 }}
spec:
  tls:
    - hosts:
        - {{ include "project-template.domain" . }}
  rules:
    - host: {{ include "project-template.domain" . }}
      http:
        paths:
          - path: "/"
            backend:
              servicePort: 80
              serviceName: {{ include "project-template.fullname" . }}
{{ end }}