kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ include "project-template.namespace" . }}
  name: {{ include "project-template.fullname" . }}
spec:
  podSelector:
    matchLabels:
      {{- include "project-template.selectorLabels" . | nindent 6 }}
  ingress:
    - from:
        - podSelector: {}