{{ $contact := .Values.contact.name }}
{{- if .Values.persistentVolumes -}}
  {{- $contact := .Values.contact.name -}}
  {{ range .Values.persistentVolumes }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ include "project-template.namespace" . }}
  name: {{ .name }}-folder
  labels:
    {{- include "project-template.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .storageSize }}Gi
---
  {{ end }}
{{ end }}