apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "project-template.fullname" . }}
  labels:
    {{- include "project-template.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}