apiVersion: v1
kind: LimitRange
metadata:
  name: default-project-limit-range
  namespace:
spec:
  limits:
  - default:
      memory: 512Mi
    defaultRequest:
      cpu: 10m
      memory: 32Mi
    type: Container


    # resources:
#   limits:
#     memory: 512Mi
#   requests:
#     cpu: 10m
#     memory: 32Mi